extend notification and add new features
entdec/signum pull request #4
Opened 2023-03-20 06:54 UTC by WaQasRPL

https://github.com/boxture/oms/issues/2725

2023-03-28 12:17 UTC, tdegrunt requested changes
Just the icon this way isn't very developer friendly.

2023-03-28 12:17 UTC, tdegrunt commented on app/components/signum/notification/component.html.slim
> +      - if @signal.icon.present?
See below, it would be more developer friendly to use `icon: 'fad fa-apple-whole'`

2023-03-29 07:36 UTC, WaQasRPL commented
made setting icon more dev friendly

`s=Signum.signal(User.first, text:"Hello World New", sticky: true, title: "this is test title", metadata: {buttons:[{title: "Google", url:"http://www.google.com"}, {title: "Apple", url: "http://www.apple.com"}], links:[{title: "Google", url:"http://www.google.com"}, {title: "Apple", url: "http://www.apple.com"}, {title: "Amazon", url: "http://www.amazon.com"}]}, icon:'fad fa-apple-whole fa-lg text-red-400')`

2023-04-12 09:32 UTC, tdegrunt approved these changes

2023-04-12 09:32 UTC, merged